"""initial schema - customers accounts check_runs check_results

Revision ID: 18f6d0868678
Revises: 
Create Date: 2026-03-03 13:04:46.933627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f6d0868678'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('slack_webhook_url', sa.Text(), nullable=True),
    sa.Column('slack_channel', sa.String(length=128), nullable=True),
    sa.Column('slack_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'profile_name', name='uq_customer_profile')
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_accounts_profile_name'), 'accounts', ['profile_name'], unique=False)
    op.create_table('check_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('check_mode', sa.String(length=32), nullable=False),
    sa.Column('check_name', sa.String(length=128), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('slack_sent', sa.Boolean(), nullable=False),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("check_mode in ('single','all','arbel')", name='ck_check_runs_mode_valid'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_check_runs_customer_created', 'check_runs', ['customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_check_runs_customer_id'), 'check_runs', ['customer_id'], unique=False)
    op.create_table('check_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('check_run_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('check_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('OK','WARN','ERROR','ALARM','NO_DATA')", name='ck_check_results_status_valid'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['check_run_id'], ['check_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_check_results_account_check', 'check_results', ['account_id', 'check_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_check_results_account_id'), 'check_results', ['account_id'], unique=False)
    op.create_index(op.f('ix_check_results_check_name'), 'check_results', ['check_name'], unique=False)
    op.create_index(op.f('ix_check_results_check_run_id'), 'check_results', ['check_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_results_check_run_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_check_name'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_account_id'), table_name='check_results')
    op.drop_index('idx_check_results_account_check', table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_check_runs_customer_id'), table_name='check_runs')
    op.drop_index('idx_check_runs_customer_created', table_name='check_runs')
    op.drop_table('check_runs')
    op.drop_index(op.f('ix_accounts_profile_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
