customer_id: ucoal
display_name: PT Ucoal
slack:
  webhook_url: ''
  channel: ''
  enabled: false
checks:
  - cost
  - guardduty
  - cloudwatch
  - notifications
accounts:
  - profile: ucoal-prod
    account_id: "637423564327"
    display_name: "Ucoal Production"
    alarm_names:
      - "TargetTracking-service/ucoal-chain-prod-ecs-cluster/ucoal-chain-prod-gateway-AlarmHigh-436a4b0b-e485-4155-aaf1-593eaef27695"
      - "TargetTracking-service/ucoal-chain-prod-ecs-cluster/ucoal-chain-prod-gateway-AlarmLow-99aebab8-95c3-4158-855a-a5b131136951"
      - "TargetTracking-service/ucoal-chain-prod-ecs-cluster/ucoal-chain-prod-master-AlarmHigh-483046f9-c4ed-4623-a466-106b55ffec5c"
      - "TargetTracking-service/ucoal-chain-prod-ecs-cluster/ucoal-chain-prod-master-AlarmHigh-c07a3761-de6a-4acd-a076-5e5d52e071e4"
      - "TargetTracking-service/ucoal-chain-prod-ecs-cluster/ucoal-chain-prod-master-AlarmLow-d193dece-807d-4b8f-971e-fc6af19cdbb9"
      - "TargetTracking-service/ucoal-chain-prod-ecs-cluster/ucoal-chain-prod-master-AlarmLow-ec342aae-3c58-4001-80bf-e1b299a823ff"
      - "TargetTracking-service/ucoal-chain-prod-ecs-cluster/ucoal-chain-prod-transaction-AlarmHigh-07e15003-58a7-44ae-8e13-462a570dceee"
      - "TargetTracking-service/ucoal-chain-prod-ecs-cluster/ucoal-chain-prod-transaction-AlarmHigh-3403cf8c-6753-40ff-a2a0-242126a24310"
      - "TargetTracking-service/ucoal-chain-prod-ecs-cluster/ucoal-chain-prod-transaction-AlarmLow-0fb846b6-cbaf-4a5a-ac5b-10ba9ffd569d"
      - "TargetTracking-service/ucoal-chain-prod-ecs-cluster/ucoal-chain-prod-transaction-AlarmLow-470d5f95-ae56-489c-9045-7fe7d6e87549"
      - "TargetTracking-ucoal-chain-dev-ecs-cluster-asg-AlarmHigh-f0466554-2163-4722-b6bb-c28cb7eea8c5"
      - "TargetTracking-ucoal-chain-dev-ecs-cluster-asg-AlarmLow-fb68c8b2-1e86-49c2-911f-b27490b576c2"
      - "TargetTracking-ucoal-chain-prod-ecs-cluster-asg-AlarmHigh-db961723-9595-4ab7-ba94-d3685cab139b"
      - "TargetTracking-ucoal-chain-prod-ecs-cluster-asg-AlarmLow-69891b9e-b836-41f9-80ba-a094bbc42c4c"
      - "ucoal-chain-dev-ecs-cluster-asg-cpu-above-85"
      - "ucoal-chain-dev-ecs-cluster-asg-statuscheckfailed"
      - "ucoal-chain-dev-ecs-cluster-cpu-reservation-above-80"
      - "ucoal-chain-dev-ecs-cluster-cpu-utilized-above-80"
      - "ucoal-chain-dev-ecs-cluster-memory-reservation-above-80"
      - "ucoal-chain-dev-pgsql-cpu-above-70"
      - "ucoal-chain-dev-pgsql-freeable-memory-lower-500mb"
      - "ucoal-chain-dev-pgsql-freestorage-space-lower-500mb"
      - "ucoal-chain-dev-service-cronjob-generator-cpu-above-80"
      - "ucoal-chain-dev-service-cronjob-generator-memory-above-80"
      - "ucoal-chain-dev-service-cronjob-generator-runtaskcount<desiredtaskcount"
      - "ucoal-chain-dev-service-gateway-cpu-above-80"
      - "ucoal-chain-dev-service-gateway-memory-above-80"
      - "ucoal-chain-dev-service-gateway-runtaskcount<desiredtaskcount"
      - "ucoal-chain-dev-service-master-cpu-above-80"
      - "ucoal-chain-dev-service-master-memory-above-80"
      - "ucoal-chain-dev-service-master-runtaskcount<desiredtaskcount"
      - "ucoal-chain-dev-service-pooling-cpu-above-80"
      - "ucoal-chain-dev-service-pooling-memory-above-80"
      - "ucoal-chain-dev-service-pooling-runtaskcount<desiredtaskcount"
      - "ucoal-chain-dev-service-transaction-cpu-above-80"
      - "ucoal-chain-dev-service-transaction-memory-above-80"
      - "ucoal-chain-dev-service-transaction-runtaskcount<desiredtaskcount"
      - "ucoal-chain-prod-ecs-cluster-asg-cpu-above-85"
      - "ucoal-chain-prod-ecs-cluster-asg-statuscheckfailed"
      - "ucoal-chain-prod-ecs-cluster-cpu-reservation-above-80"
      - "ucoal-chain-prod-ecs-cluster-cpu-utilized-above-80"
      - "ucoal-chain-prod-ecs-cluster-memory-reservation-above-80"
      - "ucoal-chain-prod-openvpn-cpu-above-70"
      - "ucoal-chain-prod-openvpn-disk-above-70"
      - "ucoal-chain-prod-openvpn-mem-above-70"
      - "ucoal-chain-prod-pgsql-cpu-above-70"
      - "ucoal-chain-prod-pgsql-freeable-memory-lower-500mb"
      - "ucoal-chain-prod-pgsql-freestorage-space-lower-500mb"
      - "ucoal-chain-prod-service-cronjob-generator-cpu-above-80"
      - "ucoal-chain-prod-service-cronjob-generator-memory-above-80"
      - "ucoal-chain-prod-service-cronjob-generator-runtaskcount<desiredtaskcount"
      - "ucoal-chain-prod-service-gateway-cpu-above-80"
      - "ucoal-chain-prod-service-gateway-memory-above-80"
      - "ucoal-chain-prod-service-gateway-runtaskcount<desiredtaskcount"
      - "ucoal-chain-prod-service-master-cpu-above-80"
      - "ucoal-chain-prod-service-master-memory-above-80"
      - "ucoal-chain-prod-service-master-runtaskcount<desiredtaskcount"
      - "ucoal-chain-prod-service-pooling-cpu-above-80"
      - "ucoal-chain-prod-service-pooling-memory-above-80"
      - "ucoal-chain-prod-service-pooling-runtaskcount<desiredtaskcount"
      - "ucoal-chain-prod-service-transaction-cpu-above-80"
      - "ucoal-chain-prod-service-transaction-memory-above-80"
      - "ucoal-chain-prod-service-transaction-runtaskcount<desiredtaskcount"
  
  - profile: ucoal-appfuel
    account_id: "593793048887"
    display_name: "Ucoal AppFuel"
    alarm_names:
      - "fuel-management-production-ucoal-apps-cpu-above-85"
      - "fuel-management-production-ucoal-apps-disk-above-85"
      - "fuel-management-production-ucoal-apps-memory-above-85"
  
  - profile: ucoal-legal
    account_id: "622022425112"
    display_name: "Ucoal Legal"
    alarm_names:
      - "UCoal-Jumphost-Server-High-CPUUtilization"
      - "UCoal-Jumphost-Server-High-DiskUsage"
      - "UCoal-Jumphost-Server-High-MemoryUtilization"
      - "UCoal-Legal-Server-High-CPUUtilization"
      - "UCoal-Legal-Server-High-DiskUsage"
      - "UCoal-Legal-Server-High-MemoryUtilization"
      - "UCoal-Marketing-Server-High-CPUUtilization"
      - "UCoal-Marketing-Server-High-DiskUsage"
      - "UCoal-Marketing-Server-High-MemoryUtilization"
      - "vpn-tunnel1-state-down-alarm"
  
  - profile: ucoal-minescape
    account_id: "595985021323"
    display_name: "Ucoal Minescape"
    alarm_names:
      - "MineScape-Prod-Apps-Server-cpu-above-80"
      - "MineScape-Prod-Apps-Server-disk-above-80"
      - "MineScape-Prod-Apps-Server-mem-above-80"
      - "MineScape-Prod-OpenVPN-cpu-above-80"
      - "MineScape-Prod-OpenVPN-disk-above-80"
      - "MineScape-Prod-OpenVPN-mem-above-80"

# Untuk menggunakan alarm_verification check, tambahkan:
# alarm_names:
#   <profile>:
#     - nama-alarm-1
#     - nama-alarm-2
