customer_id: diamond
display_name: Diamond Supermarket
sso_session: sadewa-sso

slack:
  webhook_url: ""
  channel: ""
  enabled: false

checks:
  - notifications
  - cost
  - guardduty
  - cloudwatch

accounts:
  - profile: Diamond
    account_id: "464587839665"
    display_name: "Diamond"
    alarm_names:
      - "DSM-Production-App-Disk-above-80"
      - "DSM-Production-App-cpu-above-80"
      - "DSM-Production-App-mem-above-80"
      - "DSM-Production-App-mem-above-85"
      - "DSM-Production-DB-Disk-above-80"
      - "DSM-Production-DB-cpu-above-80"
      - "DSM-Production-DB-mem-above-80"
      - "DSM-Production-OpenVPN-Disk-above-80"
      - "DSM-Production-OpenVPN-cpu-above-80"
      - "DSM-Production-OpenVPN-mem-above-80"
  - profile: kurnia-phileo
    account_id: "452439730915"
    display_name: "Kurnia Phileo Selaras - Production"
    alarm_names: []

# Untuk menggunakan alarm_verification check, tambahkan:
# alarm_names:
#   <profile>:
#     - nama-alarm-1
#     - nama-alarm-2
