customer_id: diamond
display_name: Diamond Supermarket
sso_session: sadewa-sso

slack:
  webhook_url: ""
  channel: ""
  enabled: false

checks:
  - notifications
  - cost
  - guardduty
  - cloudwatch

accounts:
  - profile: Diamond
    account_id: "464587839665"
    display_name: "Diamond"
  - profile: kurnia-phileo
    account_id: "452439730915"
    display_name: "Kurnia Phileo Selaras - Production"
