customer_id: edot
display_name: Edot
sso_session: sadewa-sso

slack:
  webhook_url: ""
  channel: ""
  enabled: false

checks:
  - notifications
  - cost
  - guardduty
  - cloudwatch

accounts:
  - profile: edot
    account_id: "261622543538"
    display_name: "Edot"
    region: ap-southeast-1
    alarm_names:
      - "elastic-node-1-disk-alarm"
      - "elastic-node-2-disk-alarm"

# Untuk menggunakan alarm_verification check, tambahkan:
# alarm_names:
#   <profile>:
#     - nama-alarm-1
#     - nama-alarm-2
