customer_id: programa
display_name: Programa Reka Piranti
slack:
  webhook_url: ''
  channel: ''
  enabled: false

checks:
  - cost
  - guardduty
  - cloudwatch
  - notifications

accounts:
  - profile: programa
    account_id: "779060063462"
    display_name: "Programa Reka Piranti"
  