customer_id: sandbox
display_name: Sandbox
sso_session: null

slack:
  webhook_url: ""
  channel: ""
  enabled: false

checks:
  - notifications
  - cost

accounts:
  - profile: sandbox
    account_id: "339712808680"
    display_name: "Sandbox"
    region: us-east-1

# Untuk menggunakan alarm_verification check, tambahkan:
# alarm_names:
#   <profile>:
#     - nama-alarm-1
#     - nama-alarm-2
