customer_id: ucoal
display_name: PT Ucoal
slack:
  webhook_url: ''
  channel: ''
  enabled: false
checks:
  - cost
  - guardduty
  - cloudwatch
  - notifications
accounts:
  - profile: ucoal-prod
    account_id: "637423564327"
    display_name: "Ucoal Production"
  
  - profile: ucoal-appfuel
    account_id: "593793048887"
    display_name: "Ucoal AppFuel"
  
  - profile: ucoal-legal
    account_id: "622022425112"
    display_name: "Ucoal Legal"
  
  - profile: ucoal-minescape
    account_id: "595985021323"
    display_name: "Ucoal Minescape"

# Untuk menggunakan alarm_verification check, tambahkan:
# alarm_names:
#   <profile>:
#     - nama-alarm-1
#     - nama-alarm-2
