"""Shared finding-event domain constants."""

from __future__ import annotations

FINDING_EVENT_CHECK_GUARDDUTY = "guardduty"
FINDING_EVENT_CHECK_CLOUDWATCH = "cloudwatch"
FINDING_EVENT_CHECK_NOTIFICATIONS = "notifications"
FINDING_EVENT_CHECK_BACKUP = "backup"

FINDING_EVENT_CHECK_NAMES = (
    FINDING_EVENT_CHECK_GUARDDUTY,
    FINDING_EVENT_CHECK_CLOUDWATCH,
    FINDING_EVENT_CHECK_NOTIFICATIONS,
    FINDING_EVENT_CHECK_BACKUP,
)
FINDING_EVENT_CHECKS = frozenset(FINDING_EVENT_CHECK_NAMES)
